---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: helmchartconfigs.helm.cattle.io
spec:
  group: helm.cattle.io
  names:
    kind: HelmChartConfig
    listKind: HelmChartConfigList
    plural: helmchartconfigs
    shortNames:
    - hcc
    singular: helmchartconfig
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: |-
          HelmChartConfig represents additional configuration for the installation of Helm chart release.
          This resource is intended for use when additional configuration needs to be passed to a HelmChart
          that is managed by an external system.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: |-
              HelmChartConfigSpec represents additional user-configurable details of an installed and configured Helm chart release.
              These fields are merged with or override the corresponding fields on the related HelmChart resource.
            properties:
              failurePolicy:
                default: reinstall
                description: |-
                  Configures handling of failed chart installation or upgrades.
                  - `reinstall` will perform a clean uninstall and reinstall of the chart.
                  - `abort` will take no action and leave the chart in a failed state so that the administrator can manually resolve the error.
                enum:
                - abort
                - reinstall
                type: string
              valuesContent:
                description: |-
                  Override complex Chart values via inline YAML content.
                  Helm CLI positional argument/flag: `--values`
                type: string
              valuesSecrets:
                description: |-
                  Override complex Chart values via references to external Secrets.
                  Helm CLI positional argument/flag: `--values`
                items:
                  description: SecretSpec describes a key in a secret to load chart
                    values from.
                  properties:
                    ignoreUpdates:
                      description: |-
                        Ignore changes to the secret, and mark the secret as optional.
                        By default, the secret must exist, and changes to the secret will trigger an upgrade of the chart to apply the updated values.
                        If `ignoreUpdates` is true, the secret is optional, and changes to the secret will not trigger an upgrade of the chart.
                      type: boolean
                    keys:
                      description: Keys to read values content from. If no keys are
                        specified, the secret is not used.
                      items:
                        type: string
                      type: array
                    name:
                      description: Name of the secret. Must be in the same namespace
                        as the HelmChart resource.
                      type: string
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
