apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller
  namespace: helm-controller
  labels:
    app: helm-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-controller
  template:
    metadata:
      labels:
        app: helm-controller
    spec:
      serviceAccountName: helm-controller
      containers:
      - name: helm-controller
        image: rancher/helm-controller:v0.12.1
        command: ["helm-controller"]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: JOB_CLUSTER_ROLE
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: DEFAULT_JOB_IMAGE
          value: "ghcr.io/k3s-io/klipper-helm:v0.9.10-build20251111"
