github:
  user: "github-actions[bot]"
  email: "41898282+github-actions[bot]@users.noreply.github.com"
  username: "UPDATECLI_GITHUB_ACTOR"
  token: "UPDATECLI_GITHUB_TOKEN"
k3s:
  org: "k3s-io"
  repo: "k3s"
  branch: "master"
kine:
  org: "k3s-io"
  repo: "kine"
  branch: "master"
k3s-upgrade:
  org: "k3s-io"
  repo: "k3s-upgrade"
  branch: "master"
go:
  org: "golang"
  repo: "go"
  branch: "master"
klipper-helm:
  org: "k3s-io"
  repo: "klipper-helm"
  branch: "master"
klipper-lb:
  org: "k3s-io"
  repo: "klipper-lb"
  branch: "master"
local-path-provisioner:
  org: "rancher"
  repo: "local-path-provisioner"
  branch: "master"
helm-controller:
  org: "k3s-io"
  repo: "helm-controller"
  branch: "master"
